In [18]:
import pandas as pd
import numpy as np
import os

In [19]:
os.getcwd()

'D:\\workspace\\DACON_2019'

In [20]:
os.chdir('D:\\workspace\\DACON_2019')

In [21]:
test = pd.read_csv('.\\SOOMIN\\data\\Test_시간별평균대치.csv')
test

Time       X26      X303      X241      X435      X402  \
0     2017-07-01 00:00:00  1.187315  0.385586  0.298691  0.276657  0.190045   
1     2017-07-01 01:00:00  1.186123  0.478955  0.307983  0.333324  0.193712   
2     2017-07-01 02:00:00  1.168301  0.467760  0.323560  0.331767  0.200656   
3     2017-07-01 03:00:00  1.163425  0.443529  0.304879  0.322123  0.189067   
4     2017-07-01 04:00:00  1.398466  0.390286  0.322174  0.320922  0.195500   
...                   ...       ...       ...       ...       ...       ...   
8755  2018-06-30 19:00:00  1.255000  0.175000  0.430000  0.429000  0.169000   
8756  2018-06-30 20:00:00  1.596000  1.692000  0.332000  0.366000  0.159000   
8757  2018-06-30 21:00:00  1.379000  0.883000  0.435000  0.497000  0.166000   
8758  2018-06-30 22:00:00  1.000000  0.539000  0.268000  0.459000  0.463000   
8759  2018-06-30 23:00:00  0.976000  0.481000  0.220000  0.418000  0.646000   

          X352      X305      X350      X326  ...      X283      X329  \
0     0.160754  0.343880  0.249761  0.070329  ...  0.288141  0.326095   
1     0.167303  0.426744  0.293231  0.072641  ...  0.259911  0.297695   
2     0.165983  0.405878  0.301436  0.076477  ...  0.237175  0.261525   
3     0.155355  0.401216  0.288693  0.082617  ...  0.203332  0.207759   
4     0.154073  0.344145  0.295861  0.074067  ...  0.189208  0.174952   
...        ...       ...       ...       ...  ...       ...       ...   
8755  0.739000  0.573000  0.341000  0.127000  ...  0.312000  0.381000   
8756  0.255000  0.501000  0.281000  0.126000  ...  0.327000  0.402000   
8757  0.233000  0.634000  0.401000  0.439000  ...  0.253000  0.401000   
8758  0.454000  0.676000  0.543000  0.737000  ...  0.332000  0.401000   
8759  0.419000  0.680000  0.499000  0.304000  ...  0.434000  0.435000   

          X223      X266        X20      X443      X347    X75   X107  \
0     0.356141  0.407326   0.159644  0.227077  0.168175  0.275  0.021   
1     0.296728  0.316149   0.159288  0.259118  0.184568  0.222  0.021   
2     0.288334  0.267332   0.157027  0.267059  0.177599  0.237  0.021   
3     0.253232  0.212221   0.154466  0.251081  0.156110  0.229  0.020   
4     0.266133  0.244444   0.152014  0.253930  0.143873  0.202  0.021   
...        ...       ...        ...       ...       ...    ...    ...   
8755  0.479000  0.858000  11.546000  0.428000  0.134000  3.519  0.027   
8756  0.725000  0.816000  11.591000  0.413000  0.206000  3.331  0.027   
8757  0.426000  0.659000  10.766000  0.466000  0.324000  3.416  0.026   
8758  0.353000  0.462000   0.312000  0.473000  0.402000  4.263  0.027   
8759  0.349000  0.792000   0.309000  0.519000  0.334000  0.784  0.027   

          X230  
0     0.338138  
1     0.335306  
2     0.344922  
3     0.334552  
4     0.346241  
...        ...  
8755  0.286000  
8756  0.303000  
8757  0.253000  
8758  0.253000  
8759  0.310000  

[8760 rows x 201 columns]

In [22]:
test['Time'] = pd.to_datetime(test['Time']) 
test = test.set_index('Time')

In [35]:
test.iloc[:, 2]

Time
2017-07-01 00:00:00    0.298691
2017-07-01 01:00:00    0.307983
2017-07-01 02:00:00    0.323560
2017-07-01 03:00:00    0.304879
2017-07-01 04:00:00    0.322174
                         ...   
2018-06-30 19:00:00    0.430000
2018-06-30 20:00:00    0.332000
2018-06-30 21:00:00    0.435000
2018-06-30 22:00:00    0.268000
2018-06-30 23:00:00    0.220000
Name: X241, Length: 8760, dtype: float64

In [24]:
from before_LSTM import *

In [25]:
before_LSTM(test.iloc[:, 2])

((8736, 24, 1), array([[[0.05615165],
         [0.0601638 ],
         [0.06498605],
         ...,
         [0.05741336],
         [0.05417953],
         [0.05225051]],
 
        [[0.05225051],
         [0.05615165],
         [0.0601638 ],
         ...,
         [0.05353517],
         [0.05741336],
         [0.05417953]],
 
        [[0.05417953],
         [0.05225051],
         [0.05615165],
         ...,
         [0.05712564],
         [0.05353517],
         [0.05741336]],
 
        ...,
 
        [[0.05916546],
         [0.07951007],
         [0.06746938],
         ...,
         [0.00207598],
         [0.0601638 ],
         [0.06498605]],
 
        [[0.08054806],
         [0.05916546],
         [0.07951007],
         ...,
         [0.05225051],
         [0.00207598],
         [0.0601638 ]],
 
        [[0.04587918],
         [0.08054806],
         [0.05916546],
         ...,
         [0.05417953],
         [0.05225051],
         [0.00207598]]]), (8736, 1), array([[0.05225051],
        

In [28]:
X_dataset_t.shape[1]

24

In [29]:
from keras.layers import LSTM 
from keras.models import Sequential 
from keras.layers import Dense 
import keras.backend as K 
from keras.callbacks import EarlyStopping

In [30]:
K.clear_session()
    
model = Sequential() # Sequeatial Model 
model.add(LSTM(20, input_shape=(X_dataset_t.shape[1], 1))) # (timestep, feature) 
model.add(Dense(1)) # output = 1 
model.compile(loss='mean_squared_error', optimizer='adam') 
model.summary()







_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 20)                1760      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 21        
Total params: 1,781
Trainable params: 1,781
Non-trainable params: 0
_________________________________________________________________


In [31]:
early_stop = EarlyStopping(monitor='loss', patience=1, verbose=1)

model.fit(X_dataset_t, y_dataset, epochs=100,
          batch_size=30, verbose=1, callbacks=[early_stop])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Epoch 1/100
8736/8736 [==============================] - 5s 557us/step - loss: 9.9708e-04
Epoch 2/100
8736/8736 [==============================] - 4s 429us/step - loss: 9.7877e-04
Epoch 3/100
8736/8736 [==============================] - 4s 443us/step - loss: 9.6089e-04
Epoch 4/100
8736/8736 [==============================] - 4s 433us/step - loss: 9.4904e-04
Epoch 5/100
8736/8736 [==============================] - 4s 414us/step - loss: 9.3427e-04
Epoch 6/100
8736/8736 [==============================] - 4s 415us/step - loss: 9.3090e-04
Epoch 7/100
8736/8736 [==============================] - 4s 433us/step - loss: 9.2763e-04
Epoch 8/100
8736/8736 [==============================] - 4s 443us/step - loss: 9.3148e-04
Epoch 00008: early stopping


In [32]:
print(X_dataset_t)

[[[0.05615165]
  [0.0601638 ]
  [0.06498605]
  ...
  [0.05741336]
  [0.05417953]
  [0.05225051]]

 [[0.05225051]
  [0.05615165]
  [0.0601638 ]
  ...
  [0.05353517]
  [0.05741336]
  [0.05417953]]

 [[0.05417953]
  [0.05225051]
  [0.05615165]
  ...
  [0.05712564]
  [0.05353517]
  [0.05741336]]

 ...

 [[0.05916546]
  [0.07951007]
  [0.06746938]
  ...
  [0.00207598]
  [0.0601638 ]
  [0.06498605]]

 [[0.08054806]
  [0.05916546]
  [0.07951007]
  ...
  [0.05225051]
  [0.00207598]
  [0.0601638 ]]

 [[0.04587918]
  [0.08054806]
  [0.05916546]
  ...
  [0.05417953]
  [0.05225051]
  [0.00207598]]]


In [33]:
before_LSTM(test.iloc[:, 2])

((8736, 24, 1), array([[[0.05615165],
         [0.0601638 ],
         [0.06498605],
         ...,
         [0.05741336],
         [0.05417953],
         [0.05225051]],
 
        [[0.05225051],
         [0.05615165],
         [0.0601638 ],
         ...,
         [0.05353517],
         [0.05741336],
         [0.05417953]],
 
        [[0.05417953],
         [0.05225051],
         [0.05615165],
         ...,
         [0.05712564],
         [0.05353517],
         [0.05741336]],
 
        ...,
 
        [[0.05916546],
         [0.07951007],
         [0.06746938],
         ...,
         [0.00207598],
         [0.0601638 ],
         [0.06498605]],
 
        [[0.08054806],
         [0.05916546],
         [0.07951007],
         ...,
         [0.05225051],
         [0.00207598],
         [0.0601638 ]],
 
        [[0.04587918],
         [0.08054806],
         [0.05916546],
         ...,
         [0.05417953],
         [0.05225051],
         [0.00207598]]]), (8736, 1), array([[0.05225051],
        

In [34]:
yhat = model.predict(X_dataset_t, verbose=1)
print(yhat)

8736/8736 [==============================] - 1s 77us/step
[[0.05653776]
 [0.05620245]
 [0.05604839]
 ...
 [0.05319199]
 [0.05288183]
 [0.04899064]]


In [38]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [44]:
yhat.tolist()

[[0.05653776228427887],
 [0.05620245262980461],
 [0.05604839324951172],
 [0.0559312179684639],
 [0.056377917528152466],
 [0.05715963989496231],
 [0.05820944160223007],
 [0.058182165026664734],
 [0.05750385671854019],
 [0.05714097619056702],
 [0.05682985484600067],
 [0.056668177247047424],
 [0.05658058822154999],
 [0.05653855949640274],
 [0.05653925612568855],
 [0.056568294763565063],
 [0.05705548822879791],
 [0.057781726121902466],
 [0.05851282924413681],
 [0.05906326696276665],
 [0.05901584401726723],
 [0.05869223177433014],
 [0.05801011621952057],
 [0.057232726365327835],
 [0.05653776228427887],
 [0.05620245262980461],
 [0.05604839324951172],
 [0.0559312179684639],
 [0.056377917528152466],
 [0.05715963989496231],
 [0.05820944160223007],
 [0.058182165026664734],
 [0.05750385671854019],
 [0.05714097619056702],
 [0.05682985484600067],
 [0.056668177247047424],
 [0.05658058822154999],
 [0.05653855949640274],
 [0.05653925612568855],
 [0.056568294763565063],
 [0.05705548822879791],
 [0.0577

In [45]:
scaler.inverse_transform(yhat.tolist())

NotFittedError: This MinMaxScaler instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [ ]:


data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
scaler = MinMaxScaler()
scaler.fit(data)    

print(scaler.transform([[2, 2]]))
Out>>> [[ 1.5  0. ]]

// This is what you need
print(scaler.inverse_transform([[ 1.5  0. ]]))
Out>>> [[ 2.0  2.0]]